### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by GeoffreyPlitt** [tsjing/socket.io-client#3]
When I run any mocha tests on files that include your module, they fail:

> mocha src/*_/_.spec.js

/Users/giro/stardust-app/node_modules/react-native-socket.io-client/socket.io.js:6381
    var objectProto = Object.prototype,
                            ^
TypeError: Cannot read property 'prototype' of undefined

**Comment by hilkeheremans** [comment]
Please run `npm run test` instead, just as in the original `socket.io-client`...

Let me know if that works for you.

**Comment by GeoffreyPlitt** [comment]
Well, I'm testing my own code, not running your tests. But simply importing your code breaks my test runner (Mocha/Istanbul), because of the fake "Object" thing that's going on near that line of code, does that make sense?

**Comment by hilkeheremans** [comment]
Related to https://github.com/socketio/socket.io/issues/2381, please check there.

**Comment by GeoffreyPlitt** [comment]
Thanks!
